version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "1111:80"
        depends_on:
            - app
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app

    db:
        image: postgres
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "tree_test"
            POSTGRES_USER: "treeTestUser"
            POSTGRES_PASSWORD: "treeTestPassword"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - "1112:5432"
        container_name: project_db
